definitions:
  Error:
    properties:
      code:
        example: 400
        format: int32
        type: integer
      message:
        description: Error message
        example: Invalid or Missing JSON Request
        type: string
    required:
      - code
      - message
  Input:
    properties:
      source:
        description: String to parse
        example: "NOTICE IS HEREBY GIVEN, pursuant to law, that the New York City Department of Consumer Affairs will hold a Public Hearing on Wednesday, January 28, 2015, at 2:00 P.M., at 66 John Street, 11th Floor, in the Borough of Manhattan, on the following petitions for sidewalk café revocable consent: 1. 132 Mulberry Inc. 132 Mulberry Street in the Borough of Manhattan"
        type: string
    required:
      - source
  StreetAddress:
    properties:
      text:
        description: Fulltext US street address
        type: string
    required:
      - text
info:
  title: "BetaNYC 5 Borough's address finder"
  version: "0.1"
paths:
  /api/parseaddresses:
    post:
      description: The only endpoint used to submit a string to be parsed.
      parameters:
        - in: body
          name: source
          schema:
            $ref: "#/definitions/Input"
      responses:
        "200":
          description: list of addresses.
          schema:
            $ref: "#/definitions/StreetAddress"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
      summary: Parse Addresses
swagger: "2.0"

